-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 16:49:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopper` DEFAULT CHARACTER SET utf8 ;
USE `shopper` ;

-- -----------------------------------------------------
-- Table `shopper`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopper`.`users` ;

CREATE TABLE IF NOT EXISTS `shopper`.`users` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopper`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopper`.`products` ;

CREATE TABLE IF NOT EXISTS `shopper`.`products` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `price` DOUBLE NOT NULL,
  `qty_stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopper`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopper`.`orders` ;

CREATE TABLE IF NOT EXISTS `shopper`.`orders` (
  `id` INT NOT NULL,
  `qty` INT NOT NULL,
  `delivery` DATE NOT NULL,
  `users_id` VARCHAR(255) NOT NULL,
  `products_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `shopper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `shopper`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
